name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to release.
        required: true

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Prepare NodeJS
        id: prepare-nodejs
        uses: chrisgavin/nodejs-prepare-action@0d5631b004aee288f3faedadacff2a9ec8f31a76
      - name: Setup NodeJS
        uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
        with:
          node-version: ${{ steps.prepare-nodejs.outputs.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Create the Release
        uses: chrisgavin/build-javascript-action-action@6ff78fb70769e6437c74a7a87712b6b0eb18c17f
        with:
          tag: ${{ github.event.inputs.tag }}
